# Generated by Django 3.1 on 2020-08-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user_name',
        ),
    ]
